---
title: "FIN5350 Essay Proposal"
author:
- affiliation: Utah State University
  name: Jesse Baker
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  pdf_document:
    citation_package: natbib
    fig_caption: yes
    keep_tex: yes
    latex_engine: pdflatex
    template: ./svm-latex-ms.tex
  word_document: default
  html_document:
    df_print: paged
biblio-style: apsr
fontfamily: mathpazo
fontsize: 11pt
geometry: margin=1in
bibliogrophy: ./master.bib
spacing: double
abstract: In this essay I address methodoligies used in economics that oversimplify
  the answers to questions concerning complex human behavior. I propose that economists
  should turn their attention more towards studying the behavior of markets, and using
  case studies, and methodological individualism to answer the underlying questions of       human behavior.
---


\newpage


## Section 1

* Buchanan's main point is that economists, in general, overemphasize the weaker, and less practical theories of economics. 

* When Buchanan speaks of *catallactics*, he is referring to the idea of trying to understand markets better to determine why prices are the way they are. He points out that too many economists focus on the theory of resource allocation, which tries to explain  how prices should be.

* Buchanan believes that economists focus too much on the problem of scarcity and resource allocation. He is worried that sollutions to problems are too narrowly defined as maximization problems, in which a pre-determined utility function is used. However, when using a fully defined utility function, choices are not made, and become purely mechanical.

* Buchanan wants economists to use the same foundational theories of economics, but by using a different thought process. He believes it is important to focus on *exchange* rather than on *choice*.

#### Introduction

To non-economists, the answer to the question "what do economists do?" is a bit ambiguous. British economist Lionel Robbins famously coined the textbook definition as "Economics is the science which studies human behavior as a relationship between ends and scarce means which have alternative uses" @Robbins1935. Since Robbins addressed the problem of scarcity so eloquently, economists have devoted the vast majority of their work to solving the riddle of how humanity deals with scarcity @buchanan. I do not contest that scarcity should be among the foundational theories of economics. However, attempting to solve the problem of scarcity has lead many economists to oversimplify human behavior. It is this oversimplification that has deviated economists from the essence of true economics, which is markets. It is in markets, contracts, and voluntary trade where we find true human behavior through agent based models, and case studies.        

#### Literature Review

In an effort to shift the mindset of the modern economist, Buchanan argues that while the foundational theories of economics are necessary, they have been used to over simplify human behavior, turning economists away from solving market behavioral problems to solving technical maximization problems @buchanan. Boettke, Palagashvili, and Lemke dissect and explain the importance of the work of Elinor Ostrom, which used case studies involving individuals pertaining to the question rather than focusing on presumption of expertise in social arrangements @boettke2013.  Lionel Robbins explained the foundational relevance of scarcity in the study of economics @robbins. Indeed, Boettke and Coyne stress the importance of methodological individualism when approaching economic question @boettke2005. 

#### Outline

1. Introduction:
    + What do Economists do?
    + What is wrong with what economists do?
    + What should they do differently

2. Literature Review:
    + @buchanan:
        + Economists focus too much on solving maximization problems that eliminate choice.
        + Economists should focus more on markets i.e. studying prices as they are, not as they should be.
    + @robbins:
        + Robbins created the textbook definition of what economists do, which is solving the problem of  scarcity.
    + @boettke2013:
        + Boettke et all praise the work of revolutionary economist Eleanor Otsrom for her research using case studies.
    + @boettke2005:
        + Stress the role of methodological individualism in economic research.


3. Representative agent models:
    + What is a RAM?
    + What are they used for?
    + Is it a good methodology for explaining how the economy works?
    
4. Case Studies:
    + What is a case study?
    + What are they used for?
    + Is it a good methodology for explaining how the economy works?
    
5. Computational game theory:
    + What is CGT?
    + What is it used for?
    + Is it a good methodology for explaining how the economy works?
    
6. Conclusion:
    + Even though the theory of scarcity is crucial in the role of economics, it has been used as a crutch to produce mediocre research methods.
    + Economists should direct their focus more towards studying actual behavior through market interaction instead of predetermined behavior through technical models.
    + Changing the mindset of how economists conduct research is paramount in describing human behavior.

<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->